name: CI
on: [pull_request]

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1

      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint:v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yaml"
          reporter: github-pr-review

  doc:
    name: Documentation
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1

      - uses: nosborn/github-action-markdown-cli@master
        with:
          files: ./content/

      - uses: K-Phoen/action-misspell@master
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          locale: "US"

      - name: alexjs
        uses: theashraf/alex-action@master

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'

      - run: make tests
        env:
          WITH_COVERAGE: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: false
